### ISSUE TITLE
输入指令l 得不到文件，有应用文件夹

### ISSUE THREAD

**Issue by cuiYuhe** [scusjs/baiduyun#10]
非常感谢分享。我现在要下载文件，看了其它issues，实在是没能领略到应该把待下载的文件放在哪个路径：
1. 看了您的教程，应该添加` 应用文件夹` ，我已经添加，但是l出不来：
![应用文件夹](https://user-images.githubusercontent.com/14869903/49335553-3864f580-f62a-11e8-9c52-3a3a9a03e889.png)
2. 输入绝对路径，也是无法识别：
![绝对路径](https://user-images.githubusercontent.com/14869903/49335560-56caf100-f62a-11e8-974d-06e6d19261ff.png)

我使用的命令是 ` python baiduyun -b`
希望得到帮助，谢谢

**Comment by scusjs** [comment]
程序运行后会自动添加应用文件夹的，然后自己的文件放在[这个目录](https://pan.baidu.com/disk/home#list/vmode=list&path=%2Fapps%2Fpcs_test_12)下即可
