### ISSUE TITLE
it doesn't work for some reasons

### ISSUE THREAD

**Issue by freestyle0** [scusjs/baiduyun#5]
Running with -b option, it can get the information of file in baiduyun, but cannot download the file with other download tools, like thunder or aria2. The address it gets could not be resoluted by download tools.

**Comment by scusjs** [comment]
it can return two urls for your file( https://d.pcs.baidu.com/*** and https://pcs.baidu.com/*** ), can any of them work?

**Comment by freestyle0** [comment]
neither of them works

**Comment by freestyle0** [comment]
I find the address could be redirected by blowser, like chrome, to the address like https://nj02all01.baidupcs.com/file/***, which is a speed-limited address.

**Comment by scusjs** [comment]
when you download files, you should set your file name in some download tools. and it can not download folder now.

**Comment by freestyle0** [comment]
I still cannot download files even if I set my file name in Aria2, it occurs an error called "HTTP authorization failed".

**Comment by scusjs** [comment]
please remove user_access_token file and try again in other download tools like thunder. i have test it in aria2 and it works well

**Comment by freestyle0** [comment]
It still doesn't work. I have already tried all the ways above and the problem still exist. I note you are using the Mac OS. Are you sure about that it still works well with Aria2 in Win8? Maybe I should specify referer and user-agent for Aria2. Would you mind show me your configuration of Aria2 for me?

**Comment by scusjs** [comment]
it can work with thunder in win10, i have not test it on win8. And in my mac, i use default configuration of aria2 for test.
