### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by Mattosx** [scusjs/baiduyun#6]
python baiduyun -b 获取数据成功，但是输入l 列出文件列表就报错了
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by scusjs** [comment]
已更新。pull 最新的程序，然后运行时加上 `--no-check-certificate` 参数

**Comment by arpit1997** [comment]
>python baiduyun -b 获取数据成功，但是输入l 列出文件列表就报错了
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
>已跟新。pull 最新的程序，然后运行时加上 参数
是输入l 列出的程序，然, ，然后运行时加上 


后运行时加上 参数, 出的程序，然, ，然后运行
