### ISSUE TITLE
输入指令l之后并未显示任何文件

### ISSUE THREAD

**Issue by kw0121** [scusjs/baiduyun#7]
![screen shot 2017-02-05 at 02 43 45](https://cloud.githubusercontent.com/assets/25561516/22624546/0b302d44-eb4d-11e6-8039-2d62b4a90742.png)

如图，文件夹下应有test文件和我后来拖入的测试文件

**Comment by scusjs** [comment]
需要将要下载的东西放到 [这个目录](https://pan.baidu.com/disk/home#list/vmode=list&path=%2Fapps%2Fpcs_test_12) 下

**Comment by kw0121** [comment]
got it! Thanks
