### ISSUE TITLE
获取文件列表返回为空

### ISSUE THREAD

**Issue by crazySyaoran** [scusjs/baiduyun#9]
登录成功：
`{u'uname': u'___Syaoran_', u'uid': u'3697910981', u'portrait': u'eadc5f5f5f5379616f72616e5f1a6d'}
获取数据成功`

但是使用参数"l"返回文件列表失败：

请输入命令:l
+--------+-------------+----------+
| 序列号 | 文件/目录名 | 文件大小 |
+--------+-------------+----------+
+--------+-------------+----------+

h 帮助
l 列出文件列表
d 获取下载地址
dl 序列获取下载地址
s 搜索文件
q 退出

我是用的`./baiduyun -b`启动的，没有装pyqt //明明我记得以前装过，但是这个程序似乎检测不到

**Any ideas?**

**另 感谢分享w**

**Comment by scusjs** [comment]
由于使用的是 PCS 接口，所以你需要提前将文件移动到应用目录，程序默认的应用目录在： [/apps/pcs_test_12](https://pan.baidu.com/disk/home?#list/vmode=list&path=%2Fapps%2Fpcs_test_12) 下，你可以点击这个链接看看下面是否存在文件。

**Comment by crazySyaoran** [comment]
已经成功了，感谢w
如果加入文件夹递归处理和指定下载目录就更好了~

祝 好

**Comment by wenxingxing** [comment]
速度又变慢辣
